// TEAM MEMBERS DATA
// Simple array of team members
// To add a new member, just copy and paste one object!

var members = [
  {
    id: 0,
    name: "Subrodh Chapagain",
    role: "Team Leader & Home Page Head",
    image: "../assests/Subrodh Chapgain.jpeg",
    age: 19,
    TechnicalSkills: "HTML, CSS, Javascript",
    Certifications: "Web Development Certificate",
    phone: "+977 9812345678",
    address: "Kathmandu, Nepal",
    studyingAt: "Islington College",
  },
  {
    id: 1,
    name: "Aabash Basnet",
    role: "Blog Page Head",
    image: "../assests//Aabash Basnet.jpeg",
    age: 20,
    TechnicalSkills: "HTML, CSS, Javascript",
    Certications: "Web Development Certificate",
    phone: "+977 9823456789",
    address: "Kathmandu, Nepal",
    studyingAt: "Islington College",
  },
  {
    id: 2,
    name: "Pyaroj Karki",
    role: "About Us & Feedback Page Head",
    image: "../assests/Pyaroj Karki.jpeg",
    age: 20,
    TechnicalSkills: "HTML, CSS, Javascript",
    Certifications: "Web Development Certificate",
    phone: "+977 9834567890",
    address: "Kathmandu, Nepal",
    studyingAt: "Pokhara University",
  },
  {
    id: 3,
    name: "Sijjan Thapa Magar",
    role: "Product Page Head",
    image: "../assests/Sijan Thapa Magar.jpeg",
    age: 20,
    TechnicalSkills: "HTML, CSS, Javascript",
    Certications: "Web Development Certificate",
    phone: "+977 9845678901",
    address: "Kathmandu, Nepal",
    studyingAt: "NCIT College",
  },
  {
    id: 4,
    name: "Aashish Shah",
    role: "Research Page Head",
    image: "../assests/Aashish Shahh.jpeg",
    age: 20,
    TechnicalSkills: "HTML, CSS, Javascript",
    Certifications: "Web Development Certificate",
    phone: "+977 9834567890",
    address: "Kathmandu, Nepal",
    studyingAt: "Islington College",
  },
];
